version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend:starter
    container_name: medusa-server-default
    environment:
      DATABASE_URL: postgres://postgres:postgres@host.docker.internal:5432/medusa
      REDIS_URL: redis://host.docker.internal
      NODE_ENV: development
      JWT_SECRET: something
      COOKIE_SECRET: something
      PORT: 9000
    ports:
      - "9000:9000"

volumes:
  node_modules:
