version: "3.8"
services:
  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa
  redis:
    image: redis
    expose:
      - 6379
    ports:
      - "6379:6379"