# version of docker compose
version: "3"
# We can setup multiple services in one go 
services: 
  # provide the name of the service, can be anything
  medusa-postgres:
    image: postgres:10.4
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa
  medusa-redis:
    image: redis
    expose:
      - 6379
    ports:
      - "6379:6379"
volumes:
  node_modules: