version: '3.8'

services:
  medusa:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      BACKEND_URL: https://7386-5-64-109-68.ngrok.io
      NODE_ENV: production
      JWT_SECRET: something
      COOKIE_SECRET: something
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/medusa
      REDIS_URL: redis://localhost:6379
      PORT: 9000